### ISSUE TITLE
Suggestions for more issue labels.

### ISSUE THREAD

**Issue by iris-i** [18F/web-design-standards-drupal-d7#37]
Opening up the conversation for adding more labels to issues for easy tracking. 
As a contributor, I would like to have extra descriptive labels for issues, so I can estimate time & effort for the task.
- discovery
- task

**Effort Level labels**
- XS
- S
- M
- L
- XL

cc: @fureigh as discussed

**Comment by fureigh** [comment]
@iris-i Thanks for this!

I'll add the `discovery` and `task` labels momentarily.

The [waffle.io board](https://waffle.io/18F/web-design-standards-drupal) supports size — would that suit your purposes?

![select-a-size](https://cloud.githubusercontent.com/assets/1244599/11885964/6318ee94-a4d9-11e5-9b59-010f7d8c5e53.png)

**Comment by fureigh** [comment]
Also wondering whether/how to distinguish between `discovery` and `question`. What do you think?

**Comment by iris-i** [comment]
@fureigh you are right, discovery is probably equivalent to questions. 
I think the underlying issue is that a few helpful options are not available to collaborators. For eg. I tested again, and confirmed that we are not able to add labels to issues. Also the ability to add size to an issue is not visible. 
<img width="310" alt="18f_web-design-standards-drupal" src="https://cloud.githubusercontent.com/assets/5355315/11887864/3eb4a192-a506-11e5-95af-af6325f4044c.png">

However, this issue is not a blocker in any way. I believe we can find an acceptable work-around and generally organize our work using other tools.

**Comment by fureigh** [comment]
@iris-i Argh, being unable to apply labels is a real challenge.

I do think those size labels are a good idea, to make tasks more clearly discoverable for potential contributors and otherwise. One potential workaround is to list them (and any other tags) in the title field when creating an issue:

> [XS] [task] Update labels

Let me know how you decide to proceed and whether there's anything I can do to make this toolset more supportive of that.

**Comment by iris-i** [comment]
@fureigh Adding the labels to the issue title sounds like a good workaround. We could adopt this format,

> [label(bug,task or question)]: [title] [(size estimate)]
> eg. Bug: Some Minor Task (XS)

**Comment by fureigh** [comment]
@iris-i Looks good to me!

(Out of scope here, but scripting something to automatically add labels based on issue titles would get around this.)

**Comment by fureigh** [comment]
Closing for now — if you need more from me here, please reopen.
