### ISSUE TITLE
Task: Add WAI-ARIA roles to sections and blocks (M)

### ISSUE THREAD

**Issue by iris-i** [18F/web-design-standards-drupal-d7#39]
As a user with disabilities, I would like to access UI components and content on the webpage easily. 
This task is for tracking the accessibility of components, by making sure that they include [Landmark roles](http://www.w3.org/TR/wai-aria-primer/#landmarks) for better navigation of content pages.

**Proposed implementation**
We can add this using JQuery instead of in the templates. This will make it easier to add new classes & components and also make sure that the page passes validation
https://www.drupal.org/node/471444

**Comment by fureigh** [comment]
Hmm — thanks for that d.o link. Accessibility is one of the USWDS's key features (and legally required), so we definitely need to prioritize accessibility concerns.

The [W3's notes on ARIA validation](http://www.w3.org/TR/aria-in-html/#aria-validation) suggest using the [W3C Nu Markup Checker](http://validator.w3.org/nu/). They further suggest:

> It is recommended that if you encounter a result that conflicts with the ARIA conformance requirements in the ARIA specification or the HTML specification, please [raise an issue](https://github.com/validator/validator/issues).

Using templates and preprocess functions seems more straightforward, reliable and performant than architecting jQuery around the fact that many HTML validators are currently outdated when it comes to ARIA attributes.

What do you think of working with templates, etc., and following the approach above for validation?

**Comment by iris-i** [comment]
I agree. If we have to choose between getting the theme validated/accessible, accessibility should be our top priority. We can open up an issue with the W3 if we encounter any problems. Also the linked d.o page is ~ 4 years old, a lot could have changed in this time.

I'll go ahead and close this issue, we will work with templates and preprocess functions to get Landmark roles in where necessary.
