### ISSUE TITLE
Add us_web_design_standards.info file (7.x-1.x)

### ISSUE THREAD

**Issue by AlexBrown-appnovation** [18F/web-design-standards-drupal-d7#5]
We should consider the following when creating this file:
1. What core stylesheets do we want to turn off by default? (if any)
2. What core scripts do we want to turn off by default? (if any)
3. What regions should we enable by default? (if any)
4. Final output for all US Web Design Standards CSS/JS files should be included and listed in proper order so nothing breaks during aggregation.
5. A useful description and screenshot should be provided.

**Comment by fureigh** [comment]
I've taken a stab at some of these in the 8.x branch. Feel free to pull anything you find useful (5, say?) from there. 1 through 3 are currently loosely based on the [Bootstrap](https://www.drupal.org/project/bootstrap) theme and are prime for revisiting; I welcome your thoughts.

**Comment by fureigh** [comment]
Closing this as addressed in #6 and #13. @AlexBrown-appnovation, if you see something here that hasn't been adequately covered, reopen this issue or comment. Thanks!
