### ISSUE TITLE
Drupal 7 or 8 theme?

### ISSUE THREAD

**Issue by Ryandaydev** [18F/web-design-standards-drupal-d7#60]
I have reviewed the issues and the readme but I wasn't 100% sure of this:
- Is the current work being done for a Drupal 7 theme? or Drupal 8 theme?

**Comment by iris-i** [comment]
Hi @rdgsa,
Both themes are being built. The drupal 8 theme is in the 8.x-1.x branch and the Drupal 7 theme is in the 7.x-1.x branch.
