### ISSUE TITLE
Correct yml path issues so that css and js files load

### ISSUE THREAD

**Issue by drnikko** [18F/web-design-standards-drupal-d7#7]
There's a small path issue in the yml files that prevents css and js files from loading.

**Comment by drnikko** [comment]
Not sure if you want Issues before PRs or just PRs so I erred on the side of process this time. :)

**Comment by fureigh** [comment]
:+1: to process. :) Thanks!

**Comment by fureigh** [comment]
Closed in #8. Thanks, @drnikki!
